version: '3.8'
services:
  glitcher-server:
    image: glitcher-server:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_URLS=http://+:8080
    volumes:
      - .:/app
      - /app/obj/
      - /app/bin/
      - /app/out/
